### ISSUE TITLE
Installer: No matching distribution found for opencv

### ISSUE THREAD

**Issue by lsq** [Surajkumarsaw1/Termux-c12#4]
ERROR: Could not find a version that satisfies the requirement opencv
ERROR: No matching distribution found for opencv

**Comment by Surajkumarsaw1** [comment]
@lsq opencv is installed but not by pip
**You could import it as **
```python 
import cv2
```
** To see image in jupyter notebook **

```python 
import matplotlib.pyplot as plt #importing matplotlib
import PIL #import PIL

# path of image (in this case in same directory (folder) so only image name )
path = 'Monerowallet.jpg'

# Displaying the image 
PIL.Image.open(str(path))

```

![Screenshot_20210204-171437_Chrome](https://user-images.githubusercontent.com/44591689/106888545-b6425100-670c-11eb-82a3-cfba15f6ced9.jpg)


**Thank you** the error messege is removed #4

**Comment by lsq** [comment]
Great, thanks!
